theme = "molokai"

[editor]
mouse = true
cursorline = true
line-number = "relative"
auto-format = false
auto-save = true
auto-info = true
true-color = true
bufferline = "multiple"
color-modes = true

[editor.soft-wrap]
enable = true

[editor.lsp]
display-messages = true
# display-signature-help-docs = false
# LSP Type Hints default is false
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spacer", "version-control", "file-name", "spinner", "diagnostics"]
right = ["position", "primary-selection-length", "total-line-numbers", "file-encoding", "file-line-ending", "file-type"]


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# 缩进提示线
[editor.indent-guides]
render = true
skip-levels = 1

[editor.file-picker]
hidden = false
