[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.basedpyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff-lsp]
command = "ruff-lsp"

[[language]]
name = "python"
roots = ["pyproject.toml"]
indent = { tab-width = 4, unit = "    " }
language-servers = ["basedpyright", "ruff-lsp"]
formatter = { command = "ruff", args = ["-"] }
auto-format = false


[[language]]
name = "bash"
file-types = [
  "sh",
  "bash",
  ".bash_login",
  ".bash_logout",
  ".bash_profile",
  ".bashrc",
  ".profile",
  ".bash_alias",
  ".bash_path",
  "host",
]

[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "    " }
file-types = ["md", "markdown"]
roots = [".git"]

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
