live_config_reload: true
tabspaces: 4
window:
  opacity: 0.85
  # 边缘空白
  padding:
    x: 18
    y: 16
  # 窗口大小
  dimensions:
    columns: 120
    lines: 60
  startup_mode: Maximized
  # 窗口修饰
  # - full: 有边界+标题栏
  # - none: 无边界+标题栏
  decorations: none

env:
  TERM: xterm-256color

import:
  - ~/.config/alacritty/theme/catppuccin-mocha.yml
# - ~/.config/alacritty/catppuccin/catppuccin-macchiato.yml
# - ~/.config/alacritty/catppuccin/catppuccin-frappe.yml
# - ~/.config/alacritty/catppuccin/catppuccin-latte.yml

shell:
  program: /bin/zsh
  args:
    - -l

scrolling:
  # 历史保留行数
  history: 2000

  # 每次滚动行数
  multiplier: 20

  # 每次滚动行数（分屏时）
  faux_multiplier: 100

  # 自动滚动至最新行
  auto_scroll: true


font:
  size: 10
  # 字体
  normal:
    family: 'FiraCode Nerd Font'
    style: Regular
  bold:
    family: 'FiraCode Nerd Font'
    style: Bold
  italic:
    family: 'FiraCode Nerd Font'
    style: Italic
  bold_italic:
    family: 'FiraCode Nerd Font'
    style: Bold Italic
  # 细描边
  AppleFontSmoothing: True

key_bindings:
  - { key: C, mods: Command, action: Copy }
  - { key: V, mods: Command, action: Paste }
  - { key: N, mods: Command, action: SpawnNewInstance }
  - { key: W, mods: Command, action: Quit }

cursor:
  # Cursor style
  #
  # Values for `style`:
  #   - Block
  #   - Underline
  #   - Beam
  style: Beam
  unfocused_hollow: true

custom_cursor_colors: true

debug:
  # Display the time it takes to redraw each frame.
  render_timer: false

  # Keep the log file after quitting Alacritty.
  persistent_logging: false

  # Log level
  #
  # Values for `log_level`:
  #   - Off
  #   - Error
  #   - Warn
  #   - Info
  #   - Debug
  #   - Trace
  log_level: Off

  # Print all received window events.
  print_events: false
