---
template:
  direction: Horizontal # 排布方向
  parts:
    - direction: Vertical # part 1，垂直分割
      borderless: true # 边框
      split_size:
        Fixed: 1
      run:
        plugin:
          location: 'zellij:tab-bar' # 加载标签栏
    - direction: Vertical # part 2
      body: true # 加载主体
    - direction: Vertical # part 3
      borderless: true
      split_size:
        Fixed: 2
      run:
        plugin:
          location: 'zellij:status-bar' # 加载状态栏

tabs: # 每个标签 pane 的排布
  - name: "tab 1" # tab 3
    direction: Vertical
    parts:
      - direction: Horizontal
        split_size:
          Percent: 70
      - direction: Horizontal
        parts:
          - direction: Horizontal
          - direction: Vertical
