[".local/share/fcitx5/themes/catppuccin-mocha-mauve/arrow.png"]
type = "file"
private = true
url = "https://raw.githubusercontent.com/catppuccin/fcitx5/393845cf3ed0e0000bfe57fe1b9ad75748e2547f/src/catppuccin-mocha-mauve/arrow.png"
checksum.sha256 = "1c6d3c28863f1e9ae79737aa8fddfaa297c26a3d669655a3d9f1fa57d63c555d"

[".local/share/fcitx5/themes/catppuccin-mocha-mauve/highlight.svg"]
type = "file"
private = true
url = "https://raw.githubusercontent.com/catppuccin/fcitx5/393845cf3ed0e0000bfe57fe1b9ad75748e2547f/src/catppuccin-mocha-mauve/highlight.svg"
checksum.sha256 = "998465b59d719effeeb3e1d6b47419326da0c4da5598b2fd5465ce61fafaa3a7"

[".local/share/fcitx5/themes/catppuccin-mocha-mauve/panel.svg"]
type = "file"
private = true
url = "https://raw.githubusercontent.com/catppuccin/fcitx5/393845cf3ed0e0000bfe57fe1b9ad75748e2547f/src/catppuccin-mocha-mauve/panel.svg"
checksum.sha256 = "210ca4ce6194ed62d1e767aa7524b489705a08d2f3e35256e361b198a66749d1"

[".local/share/fcitx5/themes/catppuccin-mocha-mauve/radio.png"]
type = "file"
private = true
url = "https://raw.githubusercontent.com/catppuccin/fcitx5/393845cf3ed0e0000bfe57fe1b9ad75748e2547f/src/catppuccin-mocha-mauve/radio.png"
checksum.sha256 = "f6a9db8febaae8af3dc23931c1a1c893d4532108773a0efac5d9ffe297d5829e"
