# Resolve ordinary unqualified images through Docker Hub.
unqualified-search-registries = ["docker.io"]
short-name-mode = "enforcing"

[aliases]
"linuxdeepin/apricot" = "docker.io/linuxdeepin/apricot"
