# My zsh config

if [ -e /home/final/.nix-profile/etc/profile.d/nix.sh ]; then . /home/final/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

if [ -d "$HOME/.cargo/bin" ] ; then
    PATH="$HOME/.cargo/bin:$PATH"

fi

# eval
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
eval "$(direnv hook zsh)"

# source plugins
source $HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source $HOME/.zsh/fsh/fast-syntax-highlighting.plugin.zsh
source $HOME/.zsh/zsh-completions/zsh-completions.plugin.zsh

# zsh config
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e


alias vi="nvim"
alias pc4="proxychains4"
alias setproxy="export ALL_PROXY=socks5://finalserver:7890; echo 'SET PROXY SUCCESS!!!'"
alias setproxylocal="export ALL_PROXY=socks5://127.0.0.1:7890; echo 'SET PROXY SUCCESS!!!'"
alias unsetproxy="unset ALL_PROXY; echo 'UNSET PROXY SUCCESS!!!'"
alias av="source .venv/bin/activate"
alias pp="export PYTHONPATH=$(pwd)"
alias tree="lsd --tree"
alias cat='bat -pp --theme="Nord"'


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/final/miniforge3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/final/miniforge3/etc/profile.d/conda.sh" ]; then
        . "/home/final/miniforge3/etc/profile.d/conda.sh"
    else
        export PATH="/home/final/miniforge3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
