# Keep the candidate window compact and visually consistent with the desktop.
Vertical Candidate List=False
WheelForPaging=True
Font="Maple Mono NF CN 11"
MenuFont="Maple Mono NF CN 10"
TrayFont="Maple Mono NF CN Bold 10"
Theme=catppuccin-mocha-mauve
DarkTheme=catppuccin-mocha-mauve
UseDarkTheme=True
UseAccentColor=False
PerScreenDPI=True
