default_shell: zsh
on_force_close: detach

simplified_ui: false # 简单 UI（不包含提示字体）
pane_frames: false # pane 之间的边框
theme: tokyo-night-storm

default_mode: normal # 启动时的模式，locked 可选
mouse_mode: true # 鼠标模式（选取）
scroll_buffer_size: 10000 # 缓冲大小

themes:
  tokyo-night-storm:
    fg: [169,177,214] #A9B1D6
    bg: [36,40,59] #24283B
    black: [56,62,90] #383E5A
    red: [249,51,87] #F9334D
    green: [158,206,106]  #9ECE6A
    yellow: [224,175,104] #E0AF68
    blue: [122,162,247]  #7AA2F7
    magenta: [187,154,247] #BB9AF7
    cyan: [42,195,222] #2AC3DE
    white: [192,202,245] #C0CAF5
    orange: [255,158,100] #FF9E64

keybinds:
  resize:
    - action: [Resize: Left]
      key: [Char: 'h', Alt: 'h']
    - action: [Resize: Right]
      key: [Char: 'l', Alt: 'l']
    - action: [Resize: Down]
      key: [Char: 'j', Alt: 'j']
    - action: [Resize: Up]
      key: [Char: 'k', Alt: 'k']
