
set-option -g mouse on

# enable utf8 support
set -q -g status-utf8 on
setw -q -g utf8 on

# Add truecolor support
set-option -ga terminal-overrides ",xterm-256color:Tc"
# Default terminal is 256 colors
set -g default-terminal "screen-256color"

# Segguested by neovim healthcheck
set-option -sa terminal-overrides ',screen-256color:RGB'
set-option -sa terminal-overrides ',XXX:RGB'

# --------------------------------------------------- 其他 -----------------------------------------------------------

#设置窗口面板起始序号
set -g base-index 1 # 设置窗口的起始下标为1
set -g pane-base-index 1 # 设置面板的起始下标为1
set -s focus-events on
set-window-option -g automatic-rename on
set-window-option -g monitor-activity on


# --------------------------------------------------- 状态栏 -----------------------------------------------------------

# set inactive/active window(pane) styles 
set -g window-style 'fg=colour247,bg=colour236'
set -g window-active-style 'fg=colour250,bg=black'
set -g status-interval 1
set -g window-status-format '#I:#(pwd="#{pane_current_path}"; echo ${pwd####*/})#F'
set -g window-status-current-format '#I:#(pwd="#{pane_current_path}"; echo ${pwd####*/})#F'

set -g pane-border-style fg='#78909C'
set -g pane-active-border-style fg='#FFD600'

# pane-border-style
# set-option -w pane-border-status off


# set -wg window-status-format " #I #W " # 状态栏窗口名称格式
# set -wg window-status-current-format " #I:#W#F " # 状态栏当前窗口名称格式(#I：序号，#w：窗口名称，#F：间隔符)
# set -wg window-status-separator "" # 状态栏窗口名称之间的间隔
# set -g message-style "bg=#202529, fg=#91A8BA" # 指定消息通知的前景、后景色


# 自定义状态栏
set -g status-interval 1 # 状态栏刷新时间
set -g status-justify left # 状态栏列表左对齐
setw -g monitor-activity on # 非当前窗口有内容更新时在状态栏通知
# --------------------------------------------------- keymap -----------------------------------------------------------


# --------------------------------------------------- linux -----------------------------------------------------------

set -g status-left "Zorn #W" # 状态栏左侧内容
set -g status-fg yellow # 设置状态栏前景黄色
set -g status-style "bg=black, fg=yellow" # 状态栏前景背景色

set -g status-right 'zorn@machine #{continuum_status}' # 状态栏右侧内容
set -g status-left-length 300 # 状态栏左边长度300
set -g status-right-length 500 # 状态栏左边长度500

set -wg window-status-current-style "bg=black" # 状态栏当前窗口名称的样式
set -wg window-status-current-style "bg=red" # 状态栏当前窗口名称的样式
set -wg window-status-last-style "fg=red" # 状态栏最后一个窗口名称的样式


set -g status-left "🐶 #W" # 状态栏左侧内容
