
set-option -g mouse on

# enable utf8 support
set -q -g status-utf8 on
setw -q -g utf8 on

# Add truecolor support
set-option -ga terminal-overrides ",xterm-256color:Tc"
# Default terminal is 256 colors
set -g default-terminal "screen-256color"

# Segguested by neovim healthcheck
set-option -sa terminal-overrides ',screen-256color:RGB'
set-option -sa terminal-overrides ',XXX:RGB'

# --------------------------------------------------- 其他 -----------------------------------------------------------

#设置窗口面板起始序号
set -g base-index 1 # 设置窗口的起始下标为1
set -g pane-base-index 1 # 设置面板的起始下标为1
set -s focus-events on
set-window-option -g automatic-rename on
set-window-option -g monitor-activity on


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @catppuccin_flavour 'mocha' # latte, frappe, macchiato, mocha

run '~/.config/tmux/plugins/tpm/tpm'
