lastupdatecheck: 0
recentrepos:
- /home/final/dotfiles
- /home/final/workspace/bid_check
- /home/final/workspace/julyfinal.github.io
startuppopupversion: 5
customcommandshistory:
- q
hidecommandlog: false
