lastupdatecheck: 0
recentrepos:
- /home/final/dotfiles
- /home/final/workspace/stable-diffusion-webui
- /home/final/dotfiles/config/alacritty/catppuccin
startuppopupversion: 5
customcommandshistory:
- q
hidecommandlog: false
