[tools]
atuin = "latest"
go = "latest"
node = "24"
npm = "12"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@earendil-works/pi-coding-agent" = { version = "latest", npm_args = "--ignore-scripts=true" }
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:@modelcontextprotocol/server-filesystem" = "latest"
"npm:@modelcontextprotocol/server-memory" = "latest"
"npm:@modelcontextprotocol/server-sequential-thinking" = "latest"
"npm:@upstash/context7-mcp" = "latest"
"npm:corepack" = "latest"
"npm:vercel" = "latest"
rust = "stable"
uv = "latest"
bat = "latest"
deno = "latest"
fzf = "latest"
fd = "latest"
navi = "latest"
rclone = "latest"
ruff = "latest"
shfmt = "latest"
starship = "latest"
stylua = "latest"
taplo = "latest"
"cargo:tree-sitter-cli" = { version = "latest", default-features = false }
"cargo:https://github.com/estin/simple-completion-language-server" = { version = "latest", locked = true }
"cargo:minijinja-cli" = "latest"
ty = "latest"
yazi = "latest"
yq = "latest"
zoxide = "latest"
agy = "latest"
lua-language-server = "latest"

[settings]
minimum_release_age = "0"

[settings.npm]
package_manager = "npm"
